name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  CARGO_TERM_COLOR: always
  PROJECT_PATH: backend/Cargo.toml

jobs:

  clippy:
    runs-on: ubuntu-latest
    name: clippy / ${{ matrix.toolchain }}
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Set up templates
        run: |
          sed -e "s/{email}/test@example.com/g" -e "s/{phone}/+1 212 555-4567/g" backend/send-contact-form-message/assets/send-error.html.tmpl >backend/send-contact-form-message/assets/send-error.html
          sed -e "s/{email}/test@example.com/g" -e "s/{phone}/+1 212 555-4567/g" backend/send-contact-form-message/assets/send-error.de.html.tmpl >backend/send-contact-form-message/assets/send-error.de.html
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path backend/Cargo.toml

  test:
    runs-on: ubuntu-latest
    name: test / ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile --manifest-path $PROJECT_PATH
      - name: Set up templates
        run: |
          sed -e "s/{email}/test@example.com/g" -e "s/{phone}/+1 212 555-4567/g" backend/send-contact-form-message/assets/send-error.html.tmpl >backend/send-contact-form-message/assets/send-error.html
          sed -e "s/{email}/test@example.com/g" -e "s/{phone}/+1 212 555-4567/g" backend/send-contact-form-message/assets/send-error.de.html.tmpl >backend/send-contact-form-message/assets/send-error.de.html
      - name: cargo test --locked
        run: cargo test --locked --manifest-path $PROJECT_PATH --bins
