name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  CARGO_TERM_COLOR: always
  PROJECT_PATH: send-contact-form-message/Cargo.toml

jobs:

  clippy:
    runs-on: ubuntu-latest
    name: clippy / ${{ matrix.toolchain }}
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path send-contact-form-message/Cargo.toml

  test:
    runs-on: ubuntu-latest
    name: test / ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install cargo-lambda
        run: python -m pip install cargo-lambda
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile --manifest-path $PROJECT_PATH
      - name: cargo lambda build --locked
        run: cargo lambda build --locked --manifest-path $PROJECT_PATH
      - name: cargo test --locked
        run: cargo test --locked --manifest-path $PROJECT_PATH
